#ifndef AUDIO_MAP_H
#define AUDIO_MAP_H

// Auto-generated by manage_assets.py

struct AudioAsset {
    int command;
    const char* filename;
};

const AudioAsset AUDIO_ASSETS[] = {
    { 100, "/boot_0_0.wav" },
    { 110, "/boot_1_0.wav" },
    { 120, "/boot_2_0.wav" },
    { 200, "/move_start_0_0.wav" },
    { 210, "/move_start_1_0.wav" },
    { 220, "/move_start_2_0.wav" },
    { 300, "/collision_0_0.wav" },
    { 301, "/collision_0_1.wav" },
    { 310, "/collision_1_0.wav" },
    { 311, "/collision_1_1.wav" },
    { 320, "/collision_2_0.wav" },
    { 321, "/collision_2_1.wav" },
    { 322, "/collision_2_2.mov" },
    { 400, "/stuck_0_0.wav" },
    { 410, "/stuck_1_0.wav" },
    { 420, "/stuck_2_0.wav" },
    { 421, "/stuck_2_1.mp3" },
    { 500, "/idle_too_long_0_0.wav" },
    { 510, "/idle_too_long_1_0.wav" },
    { 520, "/idle_too_long_2_0.wav" },
    { 600, "/reset_0_0.wav" },
    { 610, "/reset_1_0.wav" },
    { 620, "/reset_2_0.wav" },
    { 700, "/move_stop_0_0.wav" },
    { 710, "/move_stop_1_0.wav" },
    { 720, "/move_stop_2_0.wav" },
    { 800, "/mode_switch_0_0.wav" },
    { 810, "/mode_switch_1_0.wav" },
    { 820, "/mode_switch_2_0.wav" },
    { 900, "/saw_human_0_0.wav" },
    { 910, "/saw_human_1_0.wav" },
    { 920, "/saw_human_2_0.mp3" },
    { 950, "/random_0_0.mp3" },
    { 960, "/random_1_0.mov" },
    { 970, "/random_2_0.mp3" },
    { 971, "/random_2_1.mov" },
    { -1, "" } // Sentinel
};

#endif // AUDIO_MAP_H
